// <auto-generated />
namespace MPAid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class video : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(video));
        
        string IMigrationMetadata.Id
        {
            get { return "201512140526212_video"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
