using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MPAi.Cores;

namespace MPAi.Forms.MSGBox
{
    /// <summary>
    /// Class behind the form used to send feedback about MPAi.
    /// </summary>
    public partial class FeedbackScreen : Form
    {
        /// <summary>
        /// Default constructor. Shows the dialog box.
        /// </summary>
        public FeedbackScreen()
        {
            InitializeComponent();
        }
        /// <summary>
        /// Generates and sends an emial based on what has been input into the text fields.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void mailSendButton_Click(object sender, EventArgs e)
        {
            try
            {
                MailSender send = new MailSender();
                if(send.ValidateEmail(customerEmailTextBox.Text))
                {
                    MailMessage mail = new MailMessage();
                    mail.From = new MailAddress(customerEmailTextBox.Text);
                    mail.To.Add("c.watson@auckland.ac.nz");
                    mail.CC.Add("jcoo418@aucklanduni.ac.nz");
                    mail.CC.Add("tcou619@aucklanduni.ac.nz");
                    mail.CC.Add("josh.brundan@gmail.com");
                    mail.Subject = mailSubjectTextBox.Text;
                    mail.Body = string.Format("{0}{1}{2}{3}This email is sent from {4}", mailContentTextBox.Text, Environment.NewLine, Environment.NewLine, Environment.NewLine, customerEmailTextBox.Text);
                    send.Send(mail);
                    MessageBox.Show("Mail has been sent!", "Thanks!");
                    Close();
                }
                else
                {
                    MessageBox.Show("Please enter a valid email address!", "Email Address Error!");
                }
            }
            catch (Exception exp)
            {
                MessageBox.Show(exp.Message, "Message Sending Error!");
            }
        }

        /// <summary>
        /// Closes the form.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void mailCancelButton_Click(object sender, EventArgs e)
        {
            Close();
        }
    }
}
