using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using MPAid.Cores;
using NAudio.CoreAudioApi;
using System.IO;

namespace MPAid.Forms.Config
{
    /// <summary>
    /// Class for the system configuration form.
    /// </summary>
    public partial class SystemConfig : Form
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        public SystemConfig()
        {
            InitializeComponent();
        }
        /// <summary>
        /// Initialises all text boxes, and fills them in with values from the current system settings.
        /// </summary>
        public void InitializeContent()
        {
            try
            {
                // Audio folder.
                Properties.Settings.Default.AudioFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"Audio");
                InitializeTextBox(this.audioFolderTextBox, Properties.Settings.Default.AudioFolder);
                this.audioFolderTextBox.TextChanged += AudioFolderTextBox_TextChanged;
                // Video folder.
                Properties.Settings.Default.VideoFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"Video");
                InitializeTextBox(this.videoFolderTextBox, Properties.Settings.Default.VideoFolder);
                this.videoFolderTextBox.TextChanged += VideoFolderTextBox_TextChanged;
                // Recording folder.
                Properties.Settings.Default.RecordingFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"Recording");
                InitializeTextBox(this.recordingFolderTextBox, Properties.Settings.Default.RecordingFolder);
                this.recordingFolderTextBox.TextChanged += RecordingFolderTextBox_TextChanged;
                // Report folder.
                Properties.Settings.Default.ReportFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"Report");
                InitializeTextBox(this.reportFolderTextBox, Properties.Settings.Default.ReportFolder);
                this.reportFolderTextBox.TextChanged += ReportFolderTextBox_TextChanged;
                // HTK folder.
                Properties.Settings.Default.HTKFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"HTK");
                InitializeTextBox(this.HTKFolderTextBox, Properties.Settings.Default.HTKFolder);
                this.HTKFolderTextBox.TextChanged += HTKFolderTextBox_TextChanged;
                // Fomant folder.
                Properties.Settings.Default.FomantFolder = Path.Combine(System.Windows.Forms.Application.StartupPath, @"Fomant");
                InitializeTextBox(this.fomantFolderTextBox, Properties.Settings.Default.FomantFolder);
                this.fomantFolderTextBox.TextChanged += FomantFolderTextBox_TextChanged;

                Properties.Settings.Default.Save();
            }
            catch(Exception exp)
            {
                MessageBox.Show(exp.Message);
            }
        }
        /// <summary>
        /// Populates the text boxes on the form and creates the referenced directories if they don't already exist.
        /// </summary>
        /// <param name="tb">The text box to initialise.</param>
        /// <param name="dir">The directory to create (if needed) and fill the text box with.</param>
        private void InitializeTextBox(TextBox tb, string dir)
        {
            try
            {
                Directory.CreateDirectory(dir);
                tb.Text = dir;
            }
            catch(Exception exp)
            {
                MessageBox.Show(exp.Message);
            }
        }
        /// <summary>
        /// When the text in the audio text box is changed, update the location of the audio folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void AudioFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.AudioFolder = this.audioFolderTextBox.Text;
        }
        /// <summary>
        /// When the text in the video text box is changed, update the location of the video folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void VideoFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.VideoFolder = this.videoFolderTextBox.Text;
        }
        /// <summary>
        /// When the text in the recording text box is changed, update the location of the recording folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void RecordingFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.RecordingFolder = this.recordingFolderTextBox.Text;
        }
        /// <summary>
        /// When the text in the report text box is changed, update the location of the report folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void ReportFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.ReportFolder = this.reportFolderTextBox.Text;
        }
        /// <summary>
        /// When the text in the HTK text box is changed, update the location of the HTK folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void HTKFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.HTKFolder = this.HTKFolderTextBox.Text;
        }
        /// <summary>
        /// When the text in the Fomant text box is changed, update the location of the Fomant folder in the system settings.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void FomantFolderTextBox_TextChanged(object sender, EventArgs e)
        {
            Properties.Settings.Default.FomantFolder = this.fomantFolderTextBox.Text;
        }
        /// <summary>
        /// When the save button is clicked, saves the changes to the settings and closes the window.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void SaveButton_Click(object sender, EventArgs e)
        {
            Properties.Settings.Default.Save();
            this.Close();
        }
        /// <summary>
        /// When the button to select the audio folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void audioFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.audioFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
        /// <summary>
        /// When the button to select the video folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void videoFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.videoFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
        /// <summary>
        /// When the button to select the recording folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void recordingFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.recordingFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
        /// <summary>
        /// When the button to select the report folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void reportFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.reportFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
        /// <summary>
        /// When the button to select the HTK folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void HTKFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.HTKFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
        /// <summary>
        /// When the button to select the Fomant folder is clicked, opens a dialog allowing the user to navigate to their directory of choice.
        /// Once the user confirms their selection, updates the appropriate text box.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void fomantFolderSelectButton_Click(object sender, EventArgs e)
        {
            if (this.folderBrowserDialog.ShowDialog() == DialogResult.OK)
            {
                this.fomantFolderTextBox.Text = folderBrowserDialog.SelectedPath;
            }
        }
    }
}
