using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Vlc.DotNet.Core;

namespace MPAi.UserControls
{
    /// <summary>
    /// Panel containing the MPAi video player, Formant plot button and speech recognition tabs.
    /// </summary>
    public partial class OperationPanel : UserControl
    {
        /// <summary>
        /// Allows access to the VLC player field from outside the class.
        /// </summary>
        public VlcPlayer VlcPlayer
        {
            get { return vlcPlayer; }
        }
        /// <summary>
        /// Allows access to the NAudioRecorder field from outside the class.
        /// </summary>
        public NAudioRecorder NAudioRecorder
        {
            get { return naudioRecorder; }
        }
        /// <summary>
        /// Default constructor, also initialises the values for the Formant plot button.
        /// </summary>
        public OperationPanel()
        {
            InitializeComponent();

            tdButtonFormantPlot.ImageNormal = Properties.Resources.ButtonYellow_0;
            tdButtonFormantPlot.ImageHighlight = Properties.Resources.ButtonYellow_1;
            tdButtonFormantPlot.ImagePressed = Properties.Resources.ButtonYellow_2;
        }
        /// <summary>
        /// Called every time the tab is changed, updating data bindings, and ensuring the video doesn't play in the background.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void operationTabControlSelectedIndexChanged(object sender, EventArgs e)
        {
            naudioRecorder.CreateDirectory();
            naudioRecorder.DataBinding();
            VlcPlayer.VlcControl.Stop();
        }
        /// <summary>
        /// Handles the button to start up the Formant plot.
        /// The button is disabled while the plot is starting, and enabled again once it is running, preventing a race condition.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void tdButtonFormantPlot_Click(object sender, EventArgs e)
        {
            tdButtonFormantPlot.Enabled = false;

            PlotController.ClosePlot();

            tdButtonFormantPlot.Enabled = true;
        }
    }
}
