using MPAid.Cores;
using MPAid.Cores.Scoreboard;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MPAid.NewForms
{
    public partial class MPAiSoundMainMenu : Form
    {
        private bool appClosing = true;

        public MPAiSoundMainMenu()
        {
            InitializeComponent();

            // Disable score report button if the report has not been created before.
            reportButton.Enabled = (File.Exists(ReportLauncher.MPAiSoundScoreReportHTMLAddress) && File.Exists(ReportLauncher.ScoreboardReportCSSAddress));

            string name = UserManagement.getCurrentUser().getName();
            if (name == null)
            {
                greetingLabel.Text = "Kia Ora, User!";
            }
            else
            {
                greetingLabel.Text = "Kia Ora, " + name + "!";
            }
        }

        /// <summary>
        /// Fires when the form closes. 
        /// If the user pressed the back button, the next form will be loaded. 
        /// If the user closed the form in some other way, the app will temrinate.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void MPAiSoundMainMenu_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (appClosing)
            {
                UserManagement.WriteSettings();
                Properties.Settings.Default.Save();
                Application.Exit();
            }
        }

        /// <summary>
        /// Shows the learning aid for MPAi Sound - the Video Player.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void learnButton_Click(object sender, EventArgs e)
        {
            new VideoPlayer().Show();
            appClosing = false;
            Close();
        }

        /// <summary>
        /// Shows the testing aid for MPAi Sound - the Formant Plot Test.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void testButton_Click(object sender, EventArgs e)
        {
            // Launch Formant stuff
            appClosing = false;
            Close();
        }

        /// <summary>
        /// Launches the score report in the user's default browser.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void reportButton_Click(object sender, EventArgs e)
        {
            IoController.ShowInBrowser(ReportLauncher.MPAiSoundScoreReportHTMLAddress);
        }
    }
}
