using MPAid.Cores;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MPAid.NewForms
{
    public partial class MPAiSpeakMainMenu : Form
    {
        public MPAiSpeakMainMenu()
        {
            InitializeComponent();

            // Disable score report button if the report has not been created before. - THIS MAY CHANGE
            reportButton.Enabled = (File.Exists(new ReportLaucher().ScoreboardReportHTMLAddress) && File.Exists(new ReportLaucher().ScoreboardReportHTMLAddress);

            string name = UserManagement.getCurrentUser().getName();
            if (name == null)
            {
                greetingLabel.Text = "Kia Ora, User!";
            }
            else
            {
                greetingLabel.Text = "Kia Ora, " + name + "!";
            }
        }

        /// <summary>
        /// Launches the score report in the user's default browser.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void reportButton_Click(object sender, EventArgs e)
        {
            // THIS MAY CHANGE
            IoController.ShowInBrowser(new ReportLaucher().ScoreboardReportHTMLAddress);
        }
    }
}
