using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MPAid.NewForms
{

    public partial class SpeechRecognitionTest : Form
    {
        // Strings kept in fields to make text easier to change.
        private string optionsLess = "Less...";
        private string optionsMore = "More...";

        /// <summary>
        /// Default constructor.
        /// </summary>
        public SpeechRecognitionTest()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Shows/hides the options panel, changes button text, and resizes the form as appropriate.
        /// </summary>
        private void toggleOptions()
        {
            // Prevent resizing issues by storing the current height of the top panel.
            int panel1Size = SpeechRecognitionTestPanel.SplitterDistance;  
            if (SpeechRecognitionTestPanel.Panel2Collapsed)
            {
                MinimumSize = new Size(MinimumSize.Width, 600);
                optionsButton.Text = optionsLess;
            }
            else
            {
                MinimumSize = new Size(MinimumSize.Width, 250);
                Height -= (SpeechRecognitionTestPanel.Height - SpeechRecognitionTestPanel.SplitterDistance);
                optionsButton.Text = optionsMore;
            }
            SpeechRecognitionTestPanel.Panel2Collapsed = !SpeechRecognitionTestPanel.Panel2Collapsed;
            // Restore original height of the top panel.
            SpeechRecognitionTestPanel.SplitterDistance = panel1Size;
        }

        /// <summary>
        /// Functionality for the "More" and "Less" buttons.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void optionsButton_Click(object sender, EventArgs e)
        {
            toggleOptions();
        }
    }
}
