using MPAid.Cores;
using MPAid.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MPAid.NewForms
{
    public partial class VideoPlayer : Form
    {
        // Strings kept in fields to make text easier to change.
        private string vowelNotFoundText = "That sound is not valid. Try another, or select from the list.";


        public VideoPlayer()
        {
            InitializeComponent();
            populateVowelComboBox();
        }

        /// <summary>
        /// Gets the words from the database.
        /// </summary>
        private void populateVowelComboBox()
        {
            try
            {
                // Create new database context.
                using (MPAidModel DBModel = new MPAidModel())
                {
                    DBModel.Database.Initialize(false); // Added for safety; if the database has not been initialised, initialise it.

                    MPAiUser current = UserManagement.getCurrentUser();

                    List<Word> view = DBModel.Word.Where(x => (
                       x.Category.Name.Equals("Vowel")
                       //&& x.Recordings.Any(y => y.Speaker.SpeakerId == current.Speaker.SpeakerId)  // Until the Menubar is finished, this won't work. Comment this line out to test.
                       )).ToList();

                    view.Sort(new VowelComparer());
                    VowelComboBox.DataSource = new BindingSource() { DataSource = view };
                    VowelComboBox.DisplayMember = "Name";
                }
            }
            catch (Exception exp)
            {
                Console.WriteLine(exp);
            }
        }

        /// <summary>
        /// Prevents two lists appearing onscreen at once by closing the main list when the suggestion list is visible.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void VowelComboBox_KeyPress(object sender, KeyPressEventArgs e)
        {
            VowelComboBox.DroppedDown = false;
        }

        /// <summary>
        /// Ensures only valid words are entered, by comparing the text to the names of all words when focus is lost.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void VowelComboBox_Leave(object sender, EventArgs e)
        {
            //Prevents the user getting stuck when there are no words.
            if (VowelComboBox.Items.Count < 1)
            {
                return;
            }
            foreach (Word w in VowelComboBox.Items)
            {
                if (w.Name.Equals(VowelComboBox.Text))
                {
                    return;
                }
            }
            MessageBox.Show(vowelNotFoundText);
            VowelComboBox.Focus();
        }
    }
}
