using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace MPAid
{
    /// <summary>
    /// Custom button class for launching the Formant plot.
    /// </summary>
    class TDButton : Button
    {
        public Image ImageNormal;
        public Image ImageHighlight;
        public Image ImagePressed;
        /// <summary>
        /// Constructor. Adds listeners to 4 mouse events.
        /// </summary>
        public TDButton()
        {
            this.MouseDown += TDButton_MouseDown;
            this.MouseUp += TDButton_MouseUp;
            this.MouseEnter += TDButton_MouseEnter;
            this.MouseLeave += TDButton_MouseLeave;
        }
        /// <summary>
        /// When the mouse leaves, return to it's normal state.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        void TDButton_MouseLeave(object sender, EventArgs e)
        {
            this.BackgroundImage = ImageNormal;
        }
        /// <summary>
        /// When the mouse enters, highlight the button.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        void TDButton_MouseEnter(object sender, EventArgs e)
        {
            this.BackgroundImage = ImageHighlight;
        }
        /// <summary>
        /// When the button is released, returns to it's normal state.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        void TDButton_MouseUp(object sender, MouseEventArgs e)
        {
            this.BackgroundImage = ImageNormal;
        }
        /// <summary>
        /// When the button is pressed, make the button appear to sink in.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void TDButton_MouseDown(object sender, MouseEventArgs e)
        {
            this.BackgroundImage = ImagePressed;
        }
        /// <summary>
        /// Sets up the appearance and layout of the button.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // TDButton
            // 
            this.FlatAppearance.BorderSize = 0;
            this.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ResumeLayout(false);

        }

    }
}
