using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace MPAid
{
    /// <summary>
    /// Class representing the Administrator's Console form, allowing the administrator to change all user's account settings.
    /// </summary>
    public partial class AdminConsole : Form
    {
        private MPAiUser currentUser;

        /// <summary>
        /// Constructor for the application, connecting to the UserManagement object, and initialising the values in the console.
        /// </summary>
        /// <param name="users">The UserManagement object representing all current users.</param>
        public AdminConsole()
        {
            InitializeComponent();

            currentUser = UserManagement.CurrentUser;

            userDataView.DataSource = UserManagement.GetAllUsers();
            userDataView.DataBindings.Add(new Binding("ReadOnly", dataReadOnly, "Checked"));
        }

        /// <summary>
        /// Fires on closing the form. The user is asked to confirm any changes, or the form isn't closed.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void AdminConsole_FormClosing(object sender, FormClosingEventArgs e)
        {
            DialogResult dialog = MessageBox.Show("All changes you make here are permanent, and may affect other users. Are you sure?", "Confirm Changes", MessageBoxButtons.YesNo);
            if (dialog == DialogResult.Yes)
            {
                UserManagement.WriteSettings();
            }
            else
            {
                e.Cancel = true;
            }
            
        }
    }
}
