using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace MPAid
{
    /// <summary>
    /// The screen allowing a new user to be created.
    /// </summary>
    public partial class NewUserWindow : Form
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public NewUserWindow()
        {
            InitializeComponent();
        }

        private string username = null;
        private string usercode = null;

        /// <summary>
        /// Gets the values of the user from the text boxes, and uses them to create an MPAi user object.
        /// </summary>
        /// <returns>The created user object.</returns>
        public MPAiUser getCandidate()
        {
            username = userNameBox.Text;
            usercode = codeBox.Text;

            return (new MPAiUser(username, usercode));
        }

        /// <summary>
        /// Closes the window if the operation is cancelled.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void buttonCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        /// <summary>
        /// When the ok button is pressed, calls the method to verify the new user.
        /// </summary>
        /// <param name="sender">Automatically generated by Visual Studio.</param>
        /// <param name="e">Automatically generated by Visual Studio.</param>
        private void buttonOK_Click(object sender, EventArgs e) 
        {
            createUser();
        }

        /// <summary>
        /// Ensures that the new user is valid, and closes the window.
        /// </summary>
        private void createUser()
        {
            if (userNameBox.Text.Trim() == "")
            {
                MessageBox.Show("Username should not be empty! ",
                  "Ooops", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }
            else if ((codeBox.Text.Trim() == "") || (codeBox2.Text.Trim() == ""))
            {
                MessageBox.Show("Passwords should not be empty! ",
                   "Ooops", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }
            else if (codeBox.Text != codeBox2.Text)
            {
                MessageBox.Show("Passwords do not match! ",
                    "Ooops", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                return;
            }

            MPAiUser candidate = getCandidate();

            if (!UserManagement.CreateNewUser(candidate))
            {
                MessageBox.Show("User already exists, please use a different name! ",
                    "Ooops", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else
            {
                MessageBox.Show("Registration successful! ",
                        "Congratulations", MessageBoxButtons.OK, MessageBoxIcon.Information);
                UserManagement.WriteSettings();
                LoginWindow loginWindow = (LoginWindow)this.Owner;      // Only LoginWindow can open this form.
                loginWindow.VisualizeUser(candidate.getName(), candidate.getCode());
                this.Close();
            }
        }
    }
}
